###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
###############################################################

name: Build Padavan Toolchain

on:
  push:
    paths:
      - 'triggers/build-padavan-ng-tlc.md'

env:
  REPO_URL: https://github.com/zanezam/padavan-ng
  REPO_BRANCH: master
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install git build-essential gawk pkg-config gettext automake autoconf autopoint libtool bison flex zlib1g-dev libgmp3-dev libmpfr-dev libmpc-dev texinfo mc libncurses5-dev nano vim autopoint gperf python-docutils help2man libtool-bin libtool-doc
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone $REPO_URL opt/padavan-ng
        cd opt/padavan-ng
        git checkout $REPO_BRANCH

    - name: Compile toolchain
      id: compile
      run: |
        cd opt/padavan-ng/toolchain
        ./clean_sources.sh
        ./build_toolchain.sh
        echo "::set-output name=status::success"
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Prepare files
      id: prepare
      if: steps.compile.outputs.status == 'success'
      run: |
        cd opt/padavan-ng/toolchain
        tar -cJvf out.tar.xz out/*
        echo "::set-output name=status::success"

    - name: Upload toolchain
      uses: actions/upload-artifact@main
      if: steps.prepare.outputs.status == 'success'
      with:
        name: padavan-ng_toolchain_${{ env.DATE }}
        path: opt/padavan-ng/toolchain/out.tar.xz
