###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
###############################################################

name: Build Padavan Toolchain

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - 'triggers/build-padavan-tlc.md'
#   schedule:
#     - cron: 0 0 * * 1
#   watch:
#     - types: started

env:
  REPO_URL: https://github.com/vietanhbui2000/padavan
  REPO_BRANCH: main
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone $REPO_URL /opt/padavan
        cd /opt/padavan
        git checkout $REPO_BRANCH

    - name: Compile toolchain
      id: compile
      run: |
        cd /opt/padavan/toolchain-mipsel
        ./clean_toolchain
        ./build_toolchain
        echo "::set-output name=status::success"
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Prepare files
      id: prepare
      if: steps.compile.outputs.status == 'success'
      run: |
        cd /opt/padavan/toolchain-mipsel
        tar -cJvf toolchain-3.4.x.tar.xz toolchain-3.4.x/*
        echo "::set-output name=status::success"

    - name: Upload toolchain
      uses: actions/upload-artifact@main
      if: steps.prepare.outputs.status == 'success'
      with:
        name: padavan_toolchain_${{ env.DATE }}
        path: /opt/padavan/toolchain-mipsel/toolchain-3.4.x.tar.xz
