###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
###############################################################

name: Build Padavan-NG Toolchain

on:
  workflow_dispatch:

env:
  REPO_URL: https://gitlab.com/mahtabctg/padavan-ng
  REPO_BRANCH: master
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install autoconf autoconf-archive automake autopoint bison build-essential cmake cpio curl doxygen fakeroot flex gawk gettext git gperf help2man htop kmod libblkid-dev libc-ares-dev libcurl4-openssl-dev libdevmapper-dev libev-dev libevent-dev libgmp3-dev libkeyutils-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libsqlite3-dev libssl-dev libtool libtool-bin libudev-dev libxml2-dev  locales mc nano pkg-config ppp-dev python3 python3-docutils texinfo unzip uuid uuid-dev vim wget xxd zlib1g-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone $REPO_URL opt/padavan-ng
        cd opt/padavan-ng
        git checkout $REPO_BRANCH

    - name: Compile toolchain
      id: compile
      run: |
        cd opt/padavan-ng/toolchain
        ./clean_sources.sh
        ./build_toolchain.sh
        echo "::set-output name=status::success"
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Prepare files
      id: prepare
      if: steps.compile.outputs.status == 'success'
      run: |
        cd opt/padavan-ng/toolchain
        tar -cJvf out.tar.xz out/*
        echo "::set-output name=status::success"

    - name: Upload toolchain
      uses: actions/upload-artifact@main
      if: steps.prepare.outputs.status == 'success'
      with:
        name: padavan-ng_toolchain_r${{ env.DATE }}
        path: opt/padavan-ng/toolchain/out.tar.xz
