###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            hanwckf | https://github.com/hanwckf             #
###############################################################

name: Build AsusWRT

on:
  push:
    paths:
      - 'triggers/build-asuswrt.md'

env:
  REPO_URL: https://github.com/vietanhbui2000/rt-ac1200hp-asuswrt
  REPO_BRANCH: miwifi-mini
  DEVICE_NAME: miwifi-mini
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-16.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install git autoconf automake bash bison bzip2 diffutils file flex m4 g++ gawk groff-base libncurses-dev libtool libslang2 make patch perl pkg-config shtool subversion tar texinfo zlib1g zlib1g-dev git-core gettext libexpat1-dev libssl-dev cvs gperf unzip python libxml-parser-perl gcc-multilib gconf-editor libxml2-dev g++-4.7 g++-multilib libncurses5 mtd-utils libncurses5-dev libstdc++6-4.7-dev libvorbis-dev g++-4.7-multilib autopoint autogen sed build-essential intltool libglib2.0-dev xutils-dev lib32z1-dev lib32stdc++6
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone $REPO_URL asuswrt
        cd asuswrt
        git checkout $REPO_BRANCH

    - name: Prepare toolchain
      run: |
        cd asuswrt
        cp -r tools/brcm /opt/
        cp -r tools/buildroot-gcc342 /opt/

    - name: Compile firmware
      id: compile
      run: |
        export PATH=$PATH:/opt/brcm/hndtools-mipsel-linux/bin:/opt/brcm/hndtools-mipsel-uclibc/bin:/opt/buildroot-gcc342/bin
        cd asuswrt/release/src-ra-mt7620
        make -i rt-ac1200hp
        echo "::set-output name=status::success"
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload firmware
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE_NAME }}_asuswrt_${{ env.DATE }}
        path: asuswrt/release/src-ra-mt7620/image/*.trx
