###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
###############################################################

name: Build PandoraBox

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - 'triggers/build-pandorabox.md'
#   schedule:
#     - cron: 0 0 * * 1
#   watch:
#     - types: started

env:
  DEVICE_PROFILE: xiaomi-mini
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE_DIR: true
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-16.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential libncurses5-dev libncursesw5-dev \
        zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python \
        ocaml-nox help2man
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Download Image Builder
      run: |
        mkdir -p pandorabox
        cp scripts/pandorabox/dl_imagebuilder.sh pandorabox/dl_imagebuilder.sh
        cd pandorabox
        sh dl_imagebuilder.sh

    - name: Load device script
      run: |
        cp scripts/pandorabox/imagebuilder/$DEVICE_PROFILE.sh pandorabox/imagebuilder/make.sh

    - name: Compile firmware
      id: compile
      run: |
        cd pandorabox/imagebuilder
        sh make.sh
        echo "::set-output name=status::success"
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: ${{ env.DEVICE_PROFILE }}_pandorabox_bin_${{ env.DATE }}
        path: pandorabox/imagebuilder/bin

    - name: Prepare files
      id: prepare
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE_DIR == 'true'
      run: |
        cd pandorabox/imagebuilder/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.prepare.outputs.status == 'success' && env.UPLOAD_FIRMWARE_DIR == 'true'
      with:
        name: ${{ env.DEVICE_PROFILE }}_pandorabox_firmware_${{ env.DATE }}
        path: ${{ env.FIRMWARE }}
