###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            hanwckf | https://github.com/hanwckf             #
###############################################################

name: Build Padavan

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - 'triggers/build-padavan.md'
#   schedule:
#     - cron: 0 0 * * 1
#   watch:
#     - types: started

env:
  REPO_URL: https://github.com/hanwckf/rt-n56u
  REPO_BRANCH: master
  DEVICE_NAME: MiWiFi-4A
  CUSTOMIZE_FIRMWARE: false
  CUSTOMIZE_SH_FILE: scripts/padavan/customize.sh
  USE_PRECOMPILED_TOOLCHAIN: true
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone $REPO_URL /opt/rt-n56u
        cd /opt/rt-n56u
        git checkout $REPO_BRANCH

    - name: Load device configuration
      run: |
        cp -R configs/padavan/$DEVICE_NAME /opt/rt-n56u/trunk/configs/boards
        cp configs/padavan/$DEVICE_NAME.config /opt/rt-n56u/trunk/.config
        cp configs/padavan/$DEVICE_NAME.config /opt/rt-n56u/trunk/configs/templates/$DEVICE_NAME.config
        cp configs/padavan/defaults.h /opt/rt-n56u/trunk/user/shared/defaults.h

    - name: Customize firmware
      if: env.CUSTOMIZE_FIRMWARE == 'true' && !cancelled()
      run: |
        cp $CUSTOMIZE_SH_FILE /opt/rt-n56u/trunk/customize.sh
        cd /opt/rt-n56u/trunk
        chmod +x customize.sh
        ./customize.sh

    - name: Download pre-compiled toolchain
      if: env.USE_PRECOMPILED_TOOLCHAIN == 'true' && !cancelled()
      run: |
        cp scripts/padavan/dl_toolchain.sh /opt/rt-n56u/toolchain-mipsel/dl_toolchain.sh
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh

    - name: Compile toolchain
      if: env.USE_PRECOMPILED_TOOLCHAIN == 'false' && !cancelled()
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        ./clean_toolchain
        ./build_toolchain

    - name: Clean up files
      run: |
        cd /opt/rt-n56u/trunk
        ./clear_tree

    - name: Compile firmware
      run: |
        cd /opt/rt-n56u/trunk
        fakeroot ./build_firmware_modify $DEVICE_NAME
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload firmware
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.DEVICE_NAME }}_padavan_firmware_${{ env.DATE }}
        path: /opt/rt-n56u/trunk/images/*.trx
